### ISSUE TITLE
Parsing double quotation when an escape character found

### ISSUE THREAD

**Issue by kasvith** [kasvith/kache#18]
**Description**
When parsing a string with double quotations when an escape character found program detect is as unbalanced

**Steps to reproduce the behavior:**
- Start kache
- Open netcat and try `set key "val is \"something"`

**Expected behavior**
- Program must detect val is something as one sentence

**OS and Other informations**

**Additional details**

**Comment by kasvith** [comment]
Try using netcat

**Comment by Chyroc** [comment]
this can be closed

**Comment by kasvith** [comment]
tnx closing with #52
