### ISSUE TITLE
set.Intersection incorrect

### ISSUE THREAD

**Issue by BigJk** [kasvith/kache#24]
**Description**

``set.Intersection`` returns incorrect data 

**Steps to reproduce the behavior:**

```go
set1 := set.New()
set2 := set.New()
set3 := set.New()

set1.Add([]string{"a", "b", "c", "d"})
set2.Add([]string{"b"})
set3.Add([]string{"a", "b"})

inter := set.Intersection([]set.Set{*set1, *set2, *set3})
	
fmt.Println(inter)
```

prints ``[a a b b]``

**Expected behavior**

prints ``[b]``

**OS and Other informations**

**Additional details**

**Comment by kasvith** [comment]
Closes by #25
