### ISSUE TITLE
Make is troublesome

### ISSUE THREAD

**Issue by kasvith** [kasvith/kache#26]
**Description**
It's obvious that many users specially windows users find it hard to develop kache because they need to install **Make**. It would be awesome if we can introduce [mage](https://github.com/magefile/mage) for such build tasks

**Steps to reproduce the behavior:**

**Expected behavior**

**OS and Other informations**

**Additional details**

**Comment by vic3lord** [comment]
I'd also consider waiting for go 1.11 and replace dep with modules

**Comment by kasvith** [comment]
Dep is also configured, but we need a tool for run some tasks and produce binaries in correct directories.

make is fine but mage seems awesome as it can be used with anywhere that go works

**Comment by kasvith** [comment]
Closes by #60
