### ISSUE TITLE
why not initialize a reader and start the for loop

### ISSUE THREAD

**Issue by Chyroc** [kasvith/kache#33]
https://github.com/kasvith/kache/blob/6533e40265ba839b5d87c7ec07e946875e63287c/internal/srv/tcp.go#L44-L54

# 1
why not move 
```go
reader := protcl.NewReader(conn)
w := bufio.NewWriter(bufio.NewWriter(conn))
```

outside `for` loop

# 2
and  why not just wrap with
```go
w := bufio.NewWriter(conn)
```

to instead of 
```go
w := bufio.NewWriter(bufio.NewWriter(conn))
```

I am more confused, thank you for your answer.

**Comment by kasvith** [comment]
Sorry it seems there was an issue while changing the readers. Will fix that.

**Comment by kasvith** [comment]
PRs #34 #35

**Comment by kasvith** [comment]
Closes due to merge
