### ISSUE TITLE
Uppercase redis command is not supported

### ISSUE THREAD

**Issue by orangle** [kasvith/kache#54]
**Description**
Uppercase redis command is not supported

**Steps to reproduce the behavior:**
start kache
```
./bin/kache -d
```

use redis client access

```
▶ redis-cli -p 7088
127.0.0.1:7088> SET name lzz
(error) ERR: unknown command SET
127.0.0.1:7088> set name lzz
OK
```

**Expected behavior**

**OS and Other informations**
macos 

**Additional details**

**Comment by Chyroc** [comment]
update your kache and run again, this is fixed at https://github.com/kasvith/kache/pull/40
```
go get -u github.com/kasvith/kache
```

**Comment by orangle** [comment]
ok, thanks
