### ISSUE TITLE
Telnet clients broken

### ISSUE THREAD

**Issue by kasvith** [kasvith/kache#87]
**Description**
After merge of #84 the telnet client does not work anymore

**Steps to reproduce the behavior:**
- open telnet and connect to kache
- issue a command

**Expected behavior**
- reply from kache in correct format

**Actual Behavior**
- command is not parsed anymore

**OS and Other informations**

**Additional details**

**Comment by kasvith** [comment]
@Chyroc can you take a look?

**Comment by Chyroc** [comment]
![image](https://user-images.githubusercontent.com/15604894/45484734-c4802300-b787-11e8-8059-83f2a27d8309.png)
telnet send `\r\n`, but resp need only `\n`.

**Comment by kasvith** [comment]
we need to handle this mechanism to a parser which tries to process `<string>\r\n`, commands are space separated, will discuss with you soon after my exams

**Comment by kasvith** [comment]
By seeing redis authors blog he will not remove backward compatibility of resp2
So we need to mainly support RESP and we need to keep RESP3 as experimental

[Antirez's note](http://antirez.com/news/126)

So we need to revert back
